world:
  threads_num: 32
  exp_dir: "./exp/LunarLander-v2"
  exp_name: "Phi-log-fixed-power-3-5-vf-.1"

train:
  total_timesteps: 2000000
  log_interval: 10

env:
  env_id: "LunarLander-v2"
  n_envs: 32

alg: "PhiUpdate"

algo:
  policy: "MlpPolicy"
  eta: 1
  learning_rate: 0.0001
  n_steps: 16
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  normalize_advantage: False
  max_grad_norm: 0.5
  ent_coef: 0
  vf_coef: .1
  kl_coef: 1

phi:
  name: "fixed-power"
  p: 3
  q: 5
